[project]
name = "gtr"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/home/runner/workspace/gtr/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.Digital-Vault-Registry---Secure-Content-Management-Protocol]
path = "contracts/Digital-Vault-Registry---Secure-Content-Management-Protocol.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
